on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: node
      # The logic below handles the npm publication:
      - name: Checkout Git repository
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Enable Corepack
        # Required due to a limitation in setup-node https://github.com/actions/setup-node/issues/480#issuecomment-1820622085
        run: corepack enable
        if : ${{ steps.release.outputs.release_created }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: yarn
        if: ${{ steps.release.outputs.release_created }}
      - name: Install dependencies with Yarn
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --immutable
      - name: Build
        run: yarn run build
        if: ${{ steps.release.outputs.release_created }}
      - name: Lint
        run: yarn run lint
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
